# Generated by Django 4.2.4 on 2023-08-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_payment_payment_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
