# Generated by Django 4.2.4 on 2023-08-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['title'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AddField(
            model_name='course',
            name='payment_link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='стоимость'),
        ),
    ]
