# Generated by Django 4.2.4 on 2023-08-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='payment_link',
        ),
    ]
